version: '3.8'
services:
  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data

  rabbitmq:
    image: rabbitmq:3
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  postgres:
    image: postgres:9.5
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env

  web:
    image: sentry:9.1.2
    ports:
      - 9000:9000
    volumes:
      - ./sentry/:/etc/sentry/
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
      - postgres

  sentry-cron:
    image: sentry:9.1.2
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
      - postgres
    command: sentry run cron

  sentry-worker:
    image: sentry:9.1.2
    env_file:
      - .env
    deploy:
      replicas: 3
    depends_on:
      - redis
      - rabbitmq
      - postgres
    command: sentry run worker

  # nginx:
  #   restart: unless-stopped
  #   ports:
  #     - "80:80/tcp"
  #   image: "nginx:1.25.1-alpine"
  #   volumes:
  #     - type: bind
  #       read_only: true
  #       source: ./nginx
  #       target: /etc/nginx
  #   depends_on:
  #     - web

volumes:
  postgres: {}
  sentry: {}
  rabbitmq: {}
  redis: {}
